//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bajun.Network.NET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Bajun.Network.NET.RestClient.Mockup.Generated.Interfaces;
   using Bajun.Network.NET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAuraControllerMockupClient AuraControllerClient;
      public IAuraExtControllerMockupClient AuraExtControllerClient;
      public IAuthorshipControllerMockupClient AuthorshipControllerClient;
      public IAwesomeAvatarsControllerMockupClient AwesomeAvatarsControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public ICollatorSelectionControllerMockupClient CollatorSelectionControllerClient;
      public ICouncilControllerMockupClient CouncilControllerClient;
      public ICouncilMembershipControllerMockupClient CouncilMembershipControllerClient;
      public IDmpQueueControllerMockupClient DmpQueueControllerClient;
      public IIdentityControllerMockupClient IdentityControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public INftControllerMockupClient NftControllerClient;
      public INftStakeControllerMockupClient NftStakeControllerClient;
      public INftTransferControllerMockupClient NftTransferControllerClient;
      public IParachainInfoControllerMockupClient ParachainInfoControllerClient;
      public IParachainSystemControllerMockupClient ParachainSystemControllerClient;
      public IPreimageControllerMockupClient PreimageControllerClient;
      public IProxyControllerMockupClient ProxyControllerClient;
      public IRandomnessControllerMockupClient RandomnessControllerClient;
      public ISchedulerControllerMockupClient SchedulerControllerClient;
      public ISessionControllerMockupClient SessionControllerClient;
      public ISudoControllerMockupClient SudoControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public ITreasuryControllerMockupClient TreasuryControllerClient;
      public IVestingControllerMockupClient VestingControllerClient;
      public IXcmpQueueControllerMockupClient XcmpQueueControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AuraControllerClient = new AuraControllerMockupClient(_httpClient);
         AuraExtControllerClient = new AuraExtControllerMockupClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerMockupClient(_httpClient);
         AwesomeAvatarsControllerClient = new AwesomeAvatarsControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         CollatorSelectionControllerClient = new CollatorSelectionControllerMockupClient(_httpClient);
         CouncilControllerClient = new CouncilControllerMockupClient(_httpClient);
         CouncilMembershipControllerClient = new CouncilMembershipControllerMockupClient(_httpClient);
         DmpQueueControllerClient = new DmpQueueControllerMockupClient(_httpClient);
         IdentityControllerClient = new IdentityControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         NftControllerClient = new NftControllerMockupClient(_httpClient);
         NftStakeControllerClient = new NftStakeControllerMockupClient(_httpClient);
         NftTransferControllerClient = new NftTransferControllerMockupClient(_httpClient);
         ParachainInfoControllerClient = new ParachainInfoControllerMockupClient(_httpClient);
         ParachainSystemControllerClient = new ParachainSystemControllerMockupClient(_httpClient);
         PreimageControllerClient = new PreimageControllerMockupClient(_httpClient);
         ProxyControllerClient = new ProxyControllerMockupClient(_httpClient);
         RandomnessControllerClient = new RandomnessControllerMockupClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerMockupClient(_httpClient);
         SessionControllerClient = new SessionControllerMockupClient(_httpClient);
         SudoControllerClient = new SudoControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         TreasuryControllerClient = new TreasuryControllerMockupClient(_httpClient);
         VestingControllerClient = new VestingControllerMockupClient(_httpClient);
         XcmpQueueControllerClient = new XcmpQueueControllerMockupClient(_httpClient);
      }
   }
}
